version: "3.2"

services:
  mysql:
    image: mysql:8.4
    container_name: mysql_container
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - mysql-data:/var/lib/mysql
    networks:
      - s4_network

  client:
    build: ./client
    container_name: client_container
    ports:
      - 4173:4173
    environment:
      - VITE_BASE_URL=http://localhost:3000
      - VITE_HOST=0.0.0.0
    networks:
      - s4_network

  server:
    build: ./server
    container_name: server_container
    ports:
      - 3000:3000
    environment:
      - SERVER_PORT=3000
      - SERVER_HOST=0.0.0.0
      - MYSQL_URL=mysql://root:root@mysql_container/s4_sut
      - JWT_SECRET=super_secret_s4_event_password
      - SALT_WORK_FACTOR=12
    restart: always
    networks:
      - s4_network

networks:
  s4_network:

volumes:
  mysql-data:
