apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  namespace: s4-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: docker.arvancloud.ir/mysql:8.4
        ports:
        - containerPort: 3306
        envFrom:
        - configMapRef:
            name: mysql-config

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
  namespace: s4-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
        - name: server
          image: bardiark03/s4-server:v1.0.0
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: server-config

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
  namespace: s4-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
        - name: client
          image: bardiark03/s4-client:v1.0.0
          ports:
            - containerPort: 4173
          envFrom:
            - configMapRef:
                name: client-config
