POST http://localhost:3000/users
Content-Type: application/json

{
    "name" : "bardia",
    "email" : "bardia@gmail.com",
    "nationalCode" : "2081106833",
    "studentId" : "99101010",
    "attendType" : "virtual"
}